#!/usr/bin/env bash

#
# Check https://brew.sh/ for latest
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#

set -x;

# - Run these two commands in your terminal to add Homebrew to your PATH:
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/charlierobbins/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

brew install ccat
brew install git-lfs

# Update global git config
git lfs install

# Update system git config
git lfs install --system

set +x;
