[settings]
legacy_version_file = true
experimental = true
jobs = 4

[tools]
node = "lts"
python = "latest"
go = "latest"
bun = "latest"
deno = "latest"
rust = "latest"
git-cliff = "latest"
hk = "latest"
cargo-binstall = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-machete" = "latest"
"cargo:cargo-zigbuild" = "latest"
zig = "latest"
