#!/bin/zsh

#
# Check https://brew.sh/ for latest
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#

set -x;

# - Run these two commands in your terminal to add Homebrew to your PATH:
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

brew install ccat
brew install git-lfs
brew install cointop
brew install bat
brew install exa
brew install diff-so-fancy
brew install fzf
brew install duf
brew install coreutils
brew install cmake

brew install mysql
# brew services restart mysql
# brew services stop mysql

brew tap mongodb/brew
brew install mongodb-community
# To start mongodb/brew/mongodb-community now and restart at login:
#   brew services start mongodb/brew/mongodb-community
# Or, if you don't want/need a background service you can just run:
#   mongod --config /usr/local/etc/mongod.conf

set +x;
