#!/bin/zsh

#
# Check https://brew.sh/ for latest
#
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
/bin/bash -c "eval \"$(/opt/homebrew/bin/brew shellenv)\""

set -x;

# - Run these two commands in your terminal to add Homebrew to your PATH:
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

brew install gh
brew install ccat
brew install tree
brew install xsv
brew install git-lfs
brew install cointop
brew install bat
brew install exa
brew install diff-so-fancy
brew install fzf
# https://github.com/sharkdp/fd
brew install fd
brew install duf
brew install coreutils
brew install cmake
brew install pyenv

# All for LaTeX
brew install tectonic
brew install poppler
brew install latexindent

# Diagrams
brew install d2

brew install mysql
# brew services restart mysql
# brew services stop mysql
brew install postgresql

brew tap mongodb/brew
brew install mongodb-community
# To start mongodb/brew/mongodb-community now and restart at login:
#   brew services start mongodb/brew/mongodb-community
# Or, if you don't want/need a background service you can just run:
#   mongod --config /usr/local/etc/mongod.conf

brew tap espanso/espanso
brew install espanso

# Also sips
# https://rachelrly.medium.com/how-to-compress-images-in-the-mac-terminal-57f8ddd11926
brew install imagemagick

brew install charmbracelet/tap/freeze
brew install only-switch
brew install --cask eul

set +x;
