#!/bin/zsh

set -x;

# Install subl command
sudo ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl

# Install mate command
sudo ln -s /Applications/TextMate.app/Contents/MacOS/mate /usr/local/bin/mate

# Node completion
mkdir $HOME/.node-completion

set +x;
