#!/bin/zsh

set -x;

# Update global git config
git lfs install 

# Update system git config
sudo git lfs install --system --force

# gh CLI extensions moved to ./install/gh

# See also: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

# Maybe sometimes when you need https instead of ssh
# git config --global credential.helper osxkeychain


set +x;
