#!/usr/bin/env bash

pip install aider-chat

# To work with GPT-4 Turbo:
# export OPENAI_API_KEY=your-key-goes-here
# aider 

# To work with Claude 3 Opus:
# export ANTHROPIC_API_KEY=your-key-goes-here
# aider --opus
