#!/bin/zsh

set -x;

npm i -g vbump
npm i -g git-semver2-tag
npm i -g json
npm i -g http-server
npm i -g fx
npm i -g yarn
npm i -g @builder.io/micro-agent
yarn config set --home enableTelemetry 0

set +x;
