#!/usr/bin/env bash


FULLNAME=$1

IFS='/'
read -a PARTS <<< "$FULLNAME"
GIT_USER="${PARTS[0]}"
GIT_REPO="${PARTS[1]}"

if [ -z "$GIT_USER" ] || [ -z "$GIT_REPO" ]; then
  echo "Invalid input $FULLNAME"
  echo "usage: gh username/repo"
  exit 1
fi

GIT_DIR="$HOME/Git"
USER_DIR="$GIT_DIR/$GIT_USER"
REPO_DIR="$USER_DIR/$GIT_REPO"

if [ ! -d "$USER_DIR" ]; then
  echo "Creating $USER_DIR"
  mkdir -p "$USER_DIR"
fi

if [ ! -d "$REPO_DIR" ]; then
  git clone "https://github.com/$GIT_USER/$GIT_REPO" "$REPO_DIR"
fi

cd "$REPO_DIR"
