#!/bin/zsh

if [ -z $GIT_REMOTE ]; then
  GIT_REMOTE="github.com"
fi

if [ -z $GIT_ROOT ]; then
  GIT_ROOT="Git"
fi

FULLNAME="${@: -1}"

IFS='/' read -A PARTS <<< "$FULLNAME"
GIT_USER="${PARTS[1]}"
GIT_REPO="${PARTS[2]}"

echo

#
# usage()
# Prints the usage for this script
#
usage()
{
cat << EOF
usage: gh options user/repo

Changes directory into ~/Git/user/repo cloning from Github if necessary

OPTIONS:
   -s  Clone over HTTPS
   -h  Show this message.
EOF
}

GIT_URL="git@$GIT_REMOTE:$GIT_USER/$GIT_REPO"

while getopts "hs" OPTION; do
  case $OPTION in
    h)
      usage
      exit
      ;;
    s)
      GIT_URL="https://$GIT_REMOTE/$GIT_USER/$GIT_REPO"
      ;;
    \?)
      echo "$OPTION"
      usage
      exit
      ;;
  esac
done

if [ -z "$GIT_USER" ] || [ -z "$GIT_REPO" ]; then
  usage
  exit
fi

GIT_DIR="$HOME/$GIT_ROOT"
USER_DIR="$GIT_DIR/$GIT_USER"
REPO_DIR="$USER_DIR/$GIT_REPO"

if [ ! -d "$USER_DIR" ]; then
  echo "Creating $USER_DIR"
  mkdir -p "$USER_DIR"
fi

if [ ! -d "$REPO_DIR" ]; then
  echo "git clone $GIT_URL $REPO_DIR"
  git clone "$GIT_URL" "$REPO_DIR"
fi

cd "$REPO_DIR"
