#!/bin/zsh

if [ -z "$PWD" ]; then
  PWD="`pwd`"
fi

if [ -z $GIT_REMOTE ]; then
  GIT_REMOTE="github.com"
fi

BASE_DIR="`dirname $PWD`"
GIT_REPO="`basename $PWD`"
GIT_USER="`basename $BASE_DIR`"
GIT_URL="https://$GIT_REMOTE/$GIT_USER/$GIT_REPO/"

echo "open \"$GIT_URL\""
open "$GIT_URL"
