#!/usr/bin/env bash

PWD="`pwd`"
REPO="`basename $PWD`"
REMOTE_USER=$1

if [ -z $REMOTE_USER ]; then
  echo "Usage ghr user"
  exit 1
fi

if [ -z $GIT_REMOTE ]; then
  GIT_REMOTE="github.com"
fi

echo "git remote add $REMOTE_USER git@$GIT_REMOTE:$REMOTE_USER/$REPO"
git remote add "$REMOTE_USER" "git@$GIT_REMOTE:$REMOTE_USER/$REPO"
