#!/usr/bin/env bash

PWD="`pwd`"
REPO="`basename $PWD`"
REMOTE_USER=$1

if [ -z $REMOTE_USER ]; then
  echo "Usage ghr user"
  exit 1
fi

echo "git remote add $REMOTE_USER git@github.com:$REMOTE_USER/$REPO"
git remote add "$REMOTE_USER" "git@github.com:$REMOTE_USER/$REPO"