#!/usr/bin/env bash

function tag_header () {
  TAG=$1
  DATE=`date +'%Y-%m-%d'`
  HEAD="\n$TAG / $DATE\n"
  for i in $(seq 5 ${#HEAD}); do HEAD="$HEAD="; done
  HEAD="$HEAD\n\n"
  echo -e "$HEAD";
}

LAST_TAG=
for TAG in `git tag | sed '1!G;h;$!d'`; do
  if [ -z "$LAST_TAG" ]; then
    LAST_TAG=$TAG
    continue
  fi

  echo -e "$(tag_header $LAST_TAG)"
  git --no-pager log --pretty="format:  * [%h] %s" "$TAG".."$LAST_TAG"
  echo ""

  LAST_TAG=$TAG
done

