#!/bin/bash

#
# TODO: Make this work as an alias or command. 
# I suspect it has to do with bad $1 references
#

# history | awk '{print $2}' | awk 'BEGIN {FS="|"} {print $1}' | sort | uniq -c | sort -rn
history | awk '{print $2}' | awk 'BEGIN {FS="|"}{print $1}' | sort | uniq -c | sort -n | tail | sort -nr