#!/usr/bin/env bash

#
# Install Java8
#
# open http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

#
# Install Android tools
#
# https://developer.android.com/studio/index.html
# curl -O "https://dl.google.com/android/repository/tools_r25.2.4-linux.zip"
# mkdir ~/Library/Android
# unzip tools_r25.2.4-linux.zip -d ~/Library/Android/sdk
