#!/bin/bash

VERSION=
NO_NPM=
CHANGED=
DRY_RUN=
TAG_ONLY=
COMMIT_MSG=

#
# usage()
# Prints the usage for this script
#
usage()
{
cat << EOF
usage: vbump options

This commits a version bump and tags it git, then published to npm.

OPTIONS:
   -v  [required] Target version to bump.
   -t  Tag only. Do not git commit.
   -h  Show this message.
   -p  Do not publish to npm.
   -m  Commit message you wish to use.
   -d  Dry-run. No nothing but echo commands.
EOF
}

#
# checkgit()
# Ensures everything is up-to-date
#
checkgit() {
  echo "Checking git for remote updates"
  git pull --dry-run | grep -q -v 'Already up-to-date.' && CHANGED=1

  if [ ! -z $CHANGED ]; then
    echo "You need to pull from the remote before continuing"
    echo "Run 'git pull origin master'"
    exit 1
  fi
}

#
# run(@)
# Runs `cmd` unless -d (i.e. DRY_RUN) is set.
#
function run () {
  echo "$@"
  if [ -z $DRY_RUN ]; then
    "$@"
  fi
}

while getopts "v:m:hpdt" OPTION; do
  case $OPTION in
    h)
      usage
      exit
      ;;
    d)
      echo "-d: Executing dry-run..."
      DRY_RUN=1
      ;;
    t)
      echo "-t: Skipping 'git commit'"
      TAG_ONLY=1
      ;;
    p)
      echo "-p: Skipping 'npm publish'"
      NO_NPM=1
      ;;
    v)
      VERSION=$OPTARG
      ;;
    m)
      COMMIT_MSG=$OPTARG
      ;;
    \?)
      usage
      exit
      ;;
  esac
done

#
# If there is no version then exit; it is required.
#
if [ -z $VERSION ]; then
  echo "No version specified. Use -v VERSION"
  usage
  exit
fi

#
# If no custom message was supplied then use
# the default message
#
if [ -z "$COMMIT_MSG" ]; then
  COMMIT_MSG="[dist] Version bump. $VERSION"
fi

# Check git remote(s)
checkgit

#
# Run git commit only if `-t` is not set
#
if [ -z $TAG_ONLY ]; then
  run git add .
  run git commit -m "$COMMIT_MSG"
  run git push origin master
fi

#
# Always tag since we are version bumping.
#
run git tag -a "v$VERSION" -m "Version $VERSION"
run git push --tags

# Check for a package.json
if [ -z $NO_NPM ]; then
  if [ ! -f 'package.json' ]; then
    echo "No package.json file. Skipping 'npm publish'"
  else
    run npm publish
  fi
fi