#!/usr/bin/env bash

# Reduce the default DHCP lease time from 86,400 to 600 seconds to avoid
# DHCP shortage when running lots of VMs
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.InternetSharing.default.plist bootpd -dict DHCPLeaseTimeSecs -int 600
